#server:
#  port: 8888
  
spring: 
  druid: 
  #datasource: 
    #默认加载的是target目录下的文件
    url: jdbc:mysql://192.168.152.130:3306/prdatabase
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 10 #最大连接数
    min-idle: 5 #最小连接数
    max-wait: 10000 #获取连接的最大等待时间
    time-between-eviction-runs-millis: 60000 #空闲连接的检查时间间隔
    min-evictable-idle-time-millis: 300000 #空闲连接最小空闲时间
    

 